-- ============================================================
-- Healthcare Interoperability & Claims Intelligence Platform
-- Checkpoint 5A
-- Governed Analytics Physical Model
--
-- BUILD ONLY.
-- This file is not executed by Checkpoint 5A.
--
-- Model:
--   13 Dimensions
--   10 Facts
--   1 Bridge
--   53 designed analytics relationships
--
-- Safety:
--   No fact-to-fact foreign keys
--   No cross-grain financial consolidation
--   Coverage relationship remains load-gated
-- ============================================================

CREATE SCHEMA IF NOT EXISTS analytics;


-- ============================================================
-- DIMENSIONS
-- ============================================================

CREATE TABLE IF NOT EXISTS analytics.dim_date (
    date_key INTEGER PRIMARY KEY,
    calendar_date DATE NOT NULL UNIQUE,
    calendar_year SMALLINT NOT NULL,
    calendar_quarter SMALLINT NOT NULL
        CHECK (calendar_quarter BETWEEN 1 AND 4),
    month_number SMALLINT NOT NULL
        CHECK (month_number BETWEEN 1 AND 12),
    month_name TEXT NOT NULL,
    day_of_month SMALLINT NOT NULL
        CHECK (day_of_month BETWEEN 1 AND 31),
    day_of_week SMALLINT NOT NULL
        CHECK (day_of_week BETWEEN 1 AND 7),
    day_name TEXT NOT NULL,
    is_weekend BOOLEAN NOT NULL
);


CREATE TABLE IF NOT EXISTS analytics.dim_pipeline_run (
    pipeline_run_key BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    pipeline_run_id TEXT NOT NULL UNIQUE
        REFERENCES governance.pipeline_run (
            pipeline_run_id
        ),

    run_status TEXT NOT NULL,

    raw_manifest_sha256 CHAR(64),

    staging_manifest_sha256 CHAR(64),

    loaded_at TIMESTAMPTZ NOT NULL
        DEFAULT NOW(),

    CHECK (
        raw_manifest_sha256 IS NULL
        OR raw_manifest_sha256
            ~ '^[0-9A-F]{64}$'
    ),

    CHECK (
        staging_manifest_sha256 IS NULL
        OR staging_manifest_sha256
            ~ '^[0-9A-F]{64}$'
    )
);


CREATE TABLE IF NOT EXISTS analytics.dim_patient (
    patient_key BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    source_system TEXT NOT NULL,

    patient_id TEXT NOT NULL,

    birth_date DATE,

    gender TEXT,

    valid_from_pipeline_run_id TEXT NOT NULL
        REFERENCES governance.pipeline_run (
            pipeline_run_id
        ),

    valid_to_pipeline_run_id TEXT
        REFERENCES governance.pipeline_run (
            pipeline_run_id
        ),

    is_current BOOLEAN NOT NULL,

    row_hash CHAR(64) NOT NULL,

    attributes_json JSONB,

    UNIQUE (
        source_system,
        patient_id,
        valid_from_pipeline_run_id
    ),

    CHECK (
        row_hash
        ~ '^[0-9A-F]{64}$'
    ),

    CHECK (
        (
            is_current
            AND valid_to_pipeline_run_id IS NULL
        )
        OR
        (
            NOT is_current
            AND valid_to_pipeline_run_id IS NOT NULL
        )
    )
);


CREATE TABLE IF NOT EXISTS analytics.dim_coverage (
    coverage_key BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    source_system TEXT NOT NULL,

    coverage_id TEXT NOT NULL,

    coverage_status TEXT,

    subscriber_id TEXT,

    period_start DATE,

    period_end DATE,

    valid_from_pipeline_run_id TEXT NOT NULL
        REFERENCES governance.pipeline_run (
            pipeline_run_id
        ),

    valid_to_pipeline_run_id TEXT
        REFERENCES governance.pipeline_run (
            pipeline_run_id
        ),

    is_current BOOLEAN NOT NULL,

    row_hash CHAR(64) NOT NULL,

    attributes_json JSONB,

    UNIQUE (
        source_system,
        coverage_id,
        valid_from_pipeline_run_id
    ),

    CHECK (
        row_hash
        ~ '^[0-9A-F]{64}$'
    ),

    CHECK (
        period_start IS NULL
        OR period_end IS NULL
        OR period_start <= period_end
    ),

    CHECK (
        (
            is_current
            AND valid_to_pipeline_run_id IS NULL
        )
        OR
        (
            NOT is_current
            AND valid_to_pipeline_run_id IS NOT NULL
        )
    )
);


CREATE TABLE IF NOT EXISTS analytics.dim_financial_concept (
    financial_concept_key BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    system_uri TEXT NOT NULL,

    code TEXT NOT NULL,

    authority_version TEXT NOT NULL,

    authoritative_display TEXT NOT NULL,

    semantic_role TEXT NOT NULL,

    aggregation_rule TEXT NOT NULL,

    authority TEXT NOT NULL,

    authority_url TEXT NOT NULL,

    resolution_status TEXT NOT NULL,

    kpi_status TEXT NOT NULL,

    UNIQUE (
        system_uri,
        code,
        authority_version
    ),

    CHECK (
        semantic_role IN (
            'MONETARY_AMOUNT',
            'NON_MONETARY_VALUE',
            'STATUS_DISCRIMINATOR'
        )
    )
);


CREATE TABLE IF NOT EXISTS analytics.dim_currency (
    currency_key BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    currency_code TEXT NOT NULL UNIQUE,

    currency_name TEXT
);


CREATE TABLE IF NOT EXISTS analytics.dim_claim_type (
    claim_type_key BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    system_uri TEXT NOT NULL,

    code TEXT NOT NULL,

    source_display TEXT,

    authoritative_display TEXT,

    mapping_status TEXT NOT NULL,

    authority TEXT,

    authority_version TEXT,

    UNIQUE (
        system_uri,
        code
    )
);


CREATE TABLE IF NOT EXISTS analytics.dim_service_code (
    service_code_key BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    system_uri TEXT NOT NULL,

    code TEXT NOT NULL,

    source_display TEXT,

    authoritative_display TEXT,

    mapping_status TEXT NOT NULL,

    authority TEXT,

    authority_version TEXT,

    UNIQUE (
        system_uri,
        code
    )
);


CREATE TABLE IF NOT EXISTS analytics.dim_diagnosis (
    diagnosis_key BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    system_uri TEXT NOT NULL,

    code TEXT NOT NULL,

    source_display TEXT,

    authoritative_display TEXT,

    mapping_status TEXT NOT NULL,

    authority TEXT,

    authority_version TEXT,

    UNIQUE (
        system_uri,
        code
    )
);


CREATE TABLE IF NOT EXISTS analytics.dim_procedure (
    procedure_key BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    system_uri TEXT NOT NULL,

    code TEXT NOT NULL,

    source_display TEXT,

    authoritative_display TEXT,

    mapping_status TEXT NOT NULL,

    authority TEXT,

    authority_version TEXT,

    UNIQUE (
        system_uri,
        code
    )
);


CREATE TABLE IF NOT EXISTS analytics.dim_provider (
    provider_key BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    identity_key_sha256 CHAR(64) UNIQUE,

    identity_status TEXT NOT NULL,

    target_resource_type TEXT,

    identifier_system TEXT,

    identifier_value TEXT,

    display TEXT,

    is_unknown BOOLEAN NOT NULL
        DEFAULT FALSE,

    attributes_json JSONB,

    CHECK (
        (
            is_unknown
            AND identity_key_sha256 IS NULL
        )
        OR
        (
            NOT is_unknown
            AND identity_key_sha256
                ~ '^[0-9A-F]{64}$'
        )
    )
);


CREATE UNIQUE INDEX IF NOT EXISTS
uq_dim_provider_single_unknown
ON analytics.dim_provider (
    (is_unknown)
)
WHERE is_unknown;


CREATE TABLE IF NOT EXISTS analytics.dim_payer (
    payer_key BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    identity_key_sha256 CHAR(64) UNIQUE,

    identity_status TEXT NOT NULL,

    target_resource_type TEXT,

    identifier_system TEXT,

    identifier_value TEXT,

    display TEXT,

    is_unknown BOOLEAN NOT NULL
        DEFAULT FALSE,

    attributes_json JSONB,

    CHECK (
        (
            is_unknown
            AND identity_key_sha256 IS NULL
        )
        OR
        (
            NOT is_unknown
            AND identity_key_sha256
                ~ '^[0-9A-F]{64}$'
        )
    )
);


CREATE UNIQUE INDEX IF NOT EXISTS
uq_dim_payer_single_unknown
ON analytics.dim_payer (
    (is_unknown)
)
WHERE is_unknown;


CREATE TABLE IF NOT EXISTS analytics.dim_supporting_info_category (
    supporting_info_category_key BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    system_uri TEXT NOT NULL,

    code TEXT NOT NULL,

    source_display TEXT,

    authoritative_display TEXT,

    mapping_status TEXT NOT NULL,

    authority TEXT,

    authority_version TEXT,

    UNIQUE (
        system_uri,
        code
    )
);


-- ============================================================
-- FACTS
-- ============================================================

CREATE TABLE IF NOT EXISTS analytics.fact_claim (
    fact_claim_key BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    pipeline_run_key BIGINT NOT NULL
        REFERENCES analytics.dim_pipeline_run (
            pipeline_run_key
        ),

    patient_key BIGINT NOT NULL
        REFERENCES analytics.dim_patient (
            patient_key
        ),

    claim_created_date_key INTEGER NOT NULL
        REFERENCES analytics.dim_date (
            date_key
        ),

    billable_start_date_key INTEGER
        REFERENCES analytics.dim_date (
            date_key
        ),

    billable_end_date_key INTEGER
        REFERENCES analytics.dim_date (
            date_key
        ),

    claim_type_key BIGINT
        REFERENCES analytics.dim_claim_type (
            claim_type_key
        ),

    provider_key BIGINT NOT NULL
        REFERENCES analytics.dim_provider (
            provider_key
        ),

    payer_key BIGINT
        REFERENCES analytics.dim_payer (
            payer_key
        ),

    eob_id TEXT NOT NULL,

    claim_status TEXT,

    claim_use TEXT,

    claim_outcome TEXT,

    claim_row_count SMALLINT NOT NULL
        DEFAULT 1
        CHECK (claim_row_count = 1),

    source_record_hash CHAR(64) NOT NULL
        CHECK (
            source_record_hash
            ~ '^[0-9A-F]{64}$'
        ),

    UNIQUE (
        pipeline_run_key,
        eob_id
    )
);


CREATE TABLE IF NOT EXISTS analytics.fact_item (
    fact_item_key BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    pipeline_run_key BIGINT NOT NULL
        REFERENCES analytics.dim_pipeline_run (
            pipeline_run_key
        ),

    patient_key BIGINT NOT NULL
        REFERENCES analytics.dim_patient (
            patient_key
        ),

    claim_created_date_key INTEGER NOT NULL
        REFERENCES analytics.dim_date (
            date_key
        ),

    serviced_date_key INTEGER
        REFERENCES analytics.dim_date (
            date_key
        ),

    service_code_key BIGINT
        REFERENCES analytics.dim_service_code (
            service_code_key
        ),

    eob_id TEXT NOT NULL,

    item_sequence INTEGER NOT NULL,

    quantity_value NUMERIC(24,6),

    quantity_unit TEXT,

    item_row_count SMALLINT NOT NULL
        DEFAULT 1
        CHECK (item_row_count = 1),

    source_record_hash CHAR(64) NOT NULL
        CHECK (
            source_record_hash
            ~ '^[0-9A-F]{64}$'
        ),

    UNIQUE (
        pipeline_run_key,
        eob_id,
        item_sequence
    )
);


CREATE TABLE IF NOT EXISTS analytics.fact_claim_total (
    fact_claim_total_key BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    pipeline_run_key BIGINT NOT NULL
        REFERENCES analytics.dim_pipeline_run (
            pipeline_run_key
        ),

    patient_key BIGINT NOT NULL
        REFERENCES analytics.dim_patient (
            patient_key
        ),

    claim_created_date_key INTEGER NOT NULL
        REFERENCES analytics.dim_date (
            date_key
        ),

    financial_concept_key BIGINT NOT NULL
        REFERENCES analytics.dim_financial_concept (
            financial_concept_key
        ),

    currency_key BIGINT
        REFERENCES analytics.dim_currency (
            currency_key
        ),

    eob_id TEXT NOT NULL,

    source_ordinal INTEGER NOT NULL,

    amount NUMERIC(24,6),

    source_record_hash CHAR(64) NOT NULL
        CHECK (
            source_record_hash
            ~ '^[0-9A-F]{64}$'
        ),

    UNIQUE (
        pipeline_run_key,
        eob_id,
        source_ordinal
    )
);


CREATE TABLE IF NOT EXISTS analytics.fact_claim_adjudication (
    fact_claim_adjudication_key BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    pipeline_run_key BIGINT NOT NULL
        REFERENCES analytics.dim_pipeline_run (
            pipeline_run_key
        ),

    patient_key BIGINT NOT NULL
        REFERENCES analytics.dim_patient (
            patient_key
        ),

    claim_created_date_key INTEGER NOT NULL
        REFERENCES analytics.dim_date (
            date_key
        ),

    financial_concept_key BIGINT NOT NULL
        REFERENCES analytics.dim_financial_concept (
            financial_concept_key
        ),

    currency_key BIGINT
        REFERENCES analytics.dim_currency (
            currency_key
        ),

    eob_id TEXT NOT NULL,

    source_ordinal INTEGER NOT NULL,

    amount NUMERIC(24,6),

    value NUMERIC(24,6),

    source_record_hash CHAR(64) NOT NULL
        CHECK (
            source_record_hash
            ~ '^[0-9A-F]{64}$'
        ),

    UNIQUE (
        pipeline_run_key,
        eob_id,
        source_ordinal
    )
);


CREATE TABLE IF NOT EXISTS analytics.fact_item_adjudication (
    fact_item_adjudication_key BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    pipeline_run_key BIGINT NOT NULL
        REFERENCES analytics.dim_pipeline_run (
            pipeline_run_key
        ),

    patient_key BIGINT NOT NULL
        REFERENCES analytics.dim_patient (
            patient_key
        ),

    claim_created_date_key INTEGER NOT NULL
        REFERENCES analytics.dim_date (
            date_key
        ),

    financial_concept_key BIGINT NOT NULL
        REFERENCES analytics.dim_financial_concept (
            financial_concept_key
        ),

    currency_key BIGINT
        REFERENCES analytics.dim_currency (
            currency_key
        ),

    eob_id TEXT NOT NULL,

    item_sequence INTEGER NOT NULL,

    source_ordinal INTEGER NOT NULL,

    amount NUMERIC(24,6),

    source_record_hash CHAR(64) NOT NULL
        CHECK (
            source_record_hash
            ~ '^[0-9A-F]{64}$'
        ),

    UNIQUE (
        pipeline_run_key,
        eob_id,
        item_sequence,
        source_ordinal
    )
);


CREATE TABLE IF NOT EXISTS analytics.fact_diagnosis_occurrence (
    fact_diagnosis_occurrence_key BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    pipeline_run_key BIGINT NOT NULL
        REFERENCES analytics.dim_pipeline_run (
            pipeline_run_key
        ),

    patient_key BIGINT NOT NULL
        REFERENCES analytics.dim_patient (
            patient_key
        ),

    claim_created_date_key INTEGER NOT NULL
        REFERENCES analytics.dim_date (
            date_key
        ),

    diagnosis_key BIGINT
        REFERENCES analytics.dim_diagnosis (
            diagnosis_key
        ),

    eob_id TEXT NOT NULL,

    diagnosis_sequence INTEGER NOT NULL,

    diagnosis_row_count SMALLINT NOT NULL
        DEFAULT 1
        CHECK (diagnosis_row_count = 1),

    source_record_hash CHAR(64) NOT NULL
        CHECK (
            source_record_hash
            ~ '^[0-9A-F]{64}$'
        ),

    UNIQUE (
        pipeline_run_key,
        eob_id,
        diagnosis_sequence
    )
);


CREATE TABLE IF NOT EXISTS analytics.fact_procedure_occurrence (
    fact_procedure_occurrence_key BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    pipeline_run_key BIGINT NOT NULL
        REFERENCES analytics.dim_pipeline_run (
            pipeline_run_key
        ),

    patient_key BIGINT NOT NULL
        REFERENCES analytics.dim_patient (
            patient_key
        ),

    claim_created_date_key INTEGER NOT NULL
        REFERENCES analytics.dim_date (
            date_key
        ),

    procedure_date_key INTEGER
        REFERENCES analytics.dim_date (
            date_key
        ),

    procedure_key BIGINT
        REFERENCES analytics.dim_procedure (
            procedure_key
        ),

    eob_id TEXT NOT NULL,

    procedure_sequence INTEGER NOT NULL,

    procedure_row_count SMALLINT NOT NULL
        DEFAULT 1
        CHECK (procedure_row_count = 1),

    source_record_hash CHAR(64) NOT NULL
        CHECK (
            source_record_hash
            ~ '^[0-9A-F]{64}$'
        ),

    UNIQUE (
        pipeline_run_key,
        eob_id,
        procedure_sequence
    )
);


CREATE TABLE IF NOT EXISTS analytics.fact_care_team_occurrence (
    fact_care_team_occurrence_key BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    pipeline_run_key BIGINT NOT NULL
        REFERENCES analytics.dim_pipeline_run (
            pipeline_run_key
        ),

    patient_key BIGINT NOT NULL
        REFERENCES analytics.dim_patient (
            patient_key
        ),

    claim_created_date_key INTEGER NOT NULL
        REFERENCES analytics.dim_date (
            date_key
        ),

    provider_key BIGINT NOT NULL
        REFERENCES analytics.dim_provider (
            provider_key
        ),

    eob_id TEXT NOT NULL,

    careteam_sequence INTEGER NOT NULL,

    role_json JSONB,

    qualification_json JSONB,

    care_team_row_count SMALLINT NOT NULL
        DEFAULT 1
        CHECK (care_team_row_count = 1),

    source_record_hash CHAR(64) NOT NULL
        CHECK (
            source_record_hash
            ~ '^[0-9A-F]{64}$'
        ),

    UNIQUE (
        pipeline_run_key,
        eob_id,
        careteam_sequence
    )
);


CREATE TABLE IF NOT EXISTS analytics.fact_supporting_info_occurrence (
    fact_supporting_info_occurrence_key BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    pipeline_run_key BIGINT NOT NULL
        REFERENCES analytics.dim_pipeline_run (
            pipeline_run_key
        ),

    patient_key BIGINT NOT NULL
        REFERENCES analytics.dim_patient (
            patient_key
        ),

    claim_created_date_key INTEGER NOT NULL
        REFERENCES analytics.dim_date (
            date_key
        ),

    timing_date_key INTEGER
        REFERENCES analytics.dim_date (
            date_key
        ),

    supporting_info_category_key BIGINT
        REFERENCES analytics.dim_supporting_info_category (
            supporting_info_category_key
        ),

    eob_id TEXT NOT NULL,

    supporting_info_sequence INTEGER NOT NULL,

    value_string TEXT,

    code_json JSONB,

    value_quantity_json JSONB,

    supporting_info_row_count SMALLINT NOT NULL
        DEFAULT 1
        CHECK (
            supporting_info_row_count = 1
        ),

    source_record_hash CHAR(64) NOT NULL
        CHECK (
            source_record_hash
            ~ '^[0-9A-F]{64}$'
        ),

    UNIQUE (
        pipeline_run_key,
        eob_id,
        supporting_info_sequence
    )
);


CREATE TABLE IF NOT EXISTS analytics.fact_item_detail (
    fact_item_detail_key BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    pipeline_run_key BIGINT NOT NULL
        REFERENCES analytics.dim_pipeline_run (
            pipeline_run_key
        ),

    patient_key BIGINT NOT NULL
        REFERENCES analytics.dim_patient (
            patient_key
        ),

    claim_created_date_key INTEGER NOT NULL
        REFERENCES analytics.dim_date (
            date_key
        ),

    service_code_key BIGINT
        REFERENCES analytics.dim_service_code (
            service_code_key
        ),

    eob_id TEXT NOT NULL,

    item_sequence INTEGER NOT NULL,

    detail_sequence INTEGER NOT NULL,

    quantity_value NUMERIC(24,6),

    quantity_unit TEXT,

    item_detail_row_count SMALLINT NOT NULL
        DEFAULT 1
        CHECK (
            item_detail_row_count = 1
        ),

    source_record_hash CHAR(64) NOT NULL
        CHECK (
            source_record_hash
            ~ '^[0-9A-F]{64}$'
        ),

    UNIQUE (
        pipeline_run_key,
        eob_id,
        item_sequence,
        detail_sequence
    )
);


-- ============================================================
-- BRIDGE
-- ============================================================

CREATE TABLE IF NOT EXISTS analytics.bridge_claim_coverage (
    bridge_claim_coverage_key BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    association_key_sha256 CHAR(64) NOT NULL UNIQUE
        CHECK (
            association_key_sha256
            ~ '^[0-9A-F]{64}$'
        ),

    pipeline_run_key BIGINT NOT NULL
        REFERENCES analytics.dim_pipeline_run (
            pipeline_run_key
        ),

    fact_claim_key BIGINT NOT NULL
        REFERENCES analytics.fact_claim (
            fact_claim_key
        ),

    -- Intentionally nullable.
    -- Current validated run contains six
    -- DISPLAY_ONLY_NON_IDENTITY associations.
    coverage_key BIGINT NULL
        REFERENCES analytics.dim_coverage (
            coverage_key
        ),

    insurance_ordinal INTEGER NOT NULL,

    focal BOOLEAN,

    coverage_reference_form TEXT NOT NULL,

    coverage_resolution_status TEXT NOT NULL,

    coverage_display TEXT,

    source_record_hash CHAR(64) NOT NULL
        CHECK (
            source_record_hash
            ~ '^[0-9A-F]{64}$'
        ),

    UNIQUE (
        pipeline_run_key,
        fact_claim_key,
        insurance_ordinal
    )
);


-- ============================================================
-- INDEXES
-- ============================================================

CREATE INDEX IF NOT EXISTS
ix_fact_claim_run_patient
ON analytics.fact_claim (
    pipeline_run_key,
    patient_key
);

CREATE INDEX IF NOT EXISTS
ix_fact_claim_created_date
ON analytics.fact_claim (
    claim_created_date_key
);

CREATE INDEX IF NOT EXISTS
ix_fact_item_run_patient
ON analytics.fact_item (
    pipeline_run_key,
    patient_key
);

CREATE INDEX IF NOT EXISTS
ix_fact_item_service
ON analytics.fact_item (
    service_code_key
);

CREATE INDEX IF NOT EXISTS
ix_fact_claim_total_concept
ON analytics.fact_claim_total (
    financial_concept_key,
    currency_key
);

CREATE INDEX IF NOT EXISTS
ix_fact_claim_adjudication_concept
ON analytics.fact_claim_adjudication (
    financial_concept_key,
    currency_key
);

CREATE INDEX IF NOT EXISTS
ix_fact_item_adjudication_concept
ON analytics.fact_item_adjudication (
    financial_concept_key,
    currency_key
);

CREATE INDEX IF NOT EXISTS
ix_fact_diagnosis_key
ON analytics.fact_diagnosis_occurrence (
    diagnosis_key
);

CREATE INDEX IF NOT EXISTS
ix_fact_procedure_key
ON analytics.fact_procedure_occurrence (
    procedure_key
);

CREATE INDEX IF NOT EXISTS
ix_fact_care_team_provider
ON analytics.fact_care_team_occurrence (
    provider_key
);

CREATE INDEX IF NOT EXISTS
ix_fact_supporting_info_category
ON analytics.fact_supporting_info_occurrence (
    supporting_info_category_key
);

CREATE INDEX IF NOT EXISTS
ix_fact_item_detail_service
ON analytics.fact_item_detail (
    service_code_key
);

CREATE INDEX IF NOT EXISTS
ix_bridge_claim_coverage_claim
ON analytics.bridge_claim_coverage (
    fact_claim_key
);

CREATE INDEX IF NOT EXISTS
ix_bridge_claim_coverage_coverage
ON analytics.bridge_claim_coverage (
    coverage_key
)
WHERE coverage_key IS NOT NULL;
